### ISSUE TITLE
Telegram Gateway | UnexpectedValueException: Only integers, floats and strings are allowed as value

### ISSUE THREAD

**Issue by djpremier** [nextcloud/twofactor_gateway#106]
I'm from Brazil and the stack of errors below has occurred.

[nextcloud (1).log](https://github.com/nextcloud/twofactor_gateway/files/2326299/nextcloud.1.log)

**Comment by ChristophWurst** [comment]
Duplicate of #86. It looks like you didn't initiate a conversation with your telegram bot before trying to enable the app. 

Could you please provide a detailed list of what you did before you got the error?

**Comment by ChristophWurst** [comment]
Let's continue in #86 and close this one.

Thanks a lot for reporting this!
