### ISSUE TITLE
Broken 2FA after somes days

### ISSUE THREAD

**Issue by binford6000** [nextcloud/twofactor_gateway#109]
I installed nc 14 last friday and activated 2FA gateway with telegram. It worked out of the box
like a charm! Since sunday its broken. Message in the log when trying to send a verification code:

Error | PHP | Trying to get property of non-object at /var/www/cloud/apps/twofactor_gateway/lib/Service/Gateway/Telegram/Gateway.php#92 | 2018-09-18T08:28:24+0200

If you need further information please feel free to ask for!
Cheers, Sebastian

**Comment by ChristophWurst** [comment]
Hi Sebastian,

thanks a lot for your valuable feedback, especially from a Telegram user!

This could be related to #86. There are some cases the code does not yet handle well. I'll look into this.

Btw, if you have any other feedback/suggestions, please open new tickets for them. I'm very thankful for feedback that helps me/us improving this app :wink:

**Comment by binford6000** [comment]
No problem. This gateway - when it works as intended - is really great!
Before i used google authenticator and had tu pull out my iPhone. But now i can read the verficiation code directly on my Apple Watch :-)

**Comment by DotOnedotNL** [comment]
I had the same issue, after a few days the gateway errors with an "Trying to get property of non-object" error.
after issueing a /start at my telegram bot the login process is working again.
Let's wait for a few days until the login process stops again and see if the /start at the bot will resolve it.

**Comment by ChristophWurst** [comment]
I think this could be related to the bot API not returning old updates at https://github.com/nextcloud/twofactor_gateway/blob/fd4696db777867c9549269a30f7c68dc22ca7467/lib/Service/Gateway/Telegram/Gateway.php#L82, hence it breaks after a certain time.

**Comment by ChristophWurst** [comment]
Oh, there's a tiny but critical bug.

They keys at https://github.com/nextcloud/twofactor_gateway/blob/fd4696db777867c9549269a30f7c68dc22ca7467/lib/Service/Gateway/Telegram/Gateway.php#L76 and https://github.com/nextcloud/twofactor_gateway/blob/fd4696db777867c9549269a30f7c68dc22ca7467/lib/Service/Gateway/Telegram/Gateway.php#L93 don't match, hence the values isn't stored for later use.

**Comment by ChristophWurst** [comment]
If anybody is up for a simple pull request, this is your chance :wink: All that is necessary to change is the settings key as described in https://github.com/nextcloud/twofactor_gateway/issues/109#issuecomment-423880605. It should be `telegram_chat_id` on bot linked lines.

**Comment by kangaroo72** [comment]
Sorry, I'm not a dev. Is it okay, to edit the lines?
And can someone paste the lines where the chat_id is 123456 e. g.?
Thanks

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/twofactor_gateway/pull/121#issue-218202685. You'll have to setup the telegram gateway again (sorry for that). Please use the attached test build to test the patch on your system and report back if it fixes the issue or causes any others.

Thanks :v:

**Comment by binford6000** [comment]
Hi Christoph,
i applied the patch and reactivated Telegram gateway. It works again. Lets see how long ;-)
Of course i will post any changes.
Cheers, Sebastian

**Comment by ChristophWurst** [comment]
> i applied the patch and reactivated Telegram gateway. It works again. Lets see how long ;-)
> Of course i will post any changes.

Awesome, thank you Sebastian!

**Comment by DotOnedotNL** [comment]
Same for me, patch is applied, let's see...

**Comment by binford6000** [comment]
> Hi Christoph,
> i applied the patch and reactivated Telegram gateway. It works again. Lets see how long ;-)
> Of course i will post any changes.
> Cheers, Sebastian

After two days and many logons with 2FA: works like a charm again! :-)

**Comment by ChristophWurst** [comment]
> After two days and many logons with 2FA: works like a charm again! :-)

Thanks a lot. This is great to hear!

I will, however, wait with releasing a new version until Monday. Releasing by the end of the week is never a great again because nobody is around if quickfixes are required :wink:
