### ISSUE TITLE
Disabled Telegram two days before - enabled today, now the TG-ID will not work anymore

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/twofactor_gateway#118]
Hi,

I've disabled the TG-Auth two days before, 'cause I did not setup the app-codes.
Today I wanted to enable again, but it's not able to verify my TG-ID.
Is this a bug?

Best

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/twofactor_gateway/issues/109.
