### ISSUE TITLE
How to configure this plugin?

### ISSUE THREAD

**Issue by loskiq** [nextcloud/twofactor_gateway#127]
```
occ twofactorauth:gateway:configure telegram
````

What is this?

```
root@debian:~# occ twofactorauth:gateway:configure telegram
-bash: occ: command not found
```

I don't understand.

**Comment by ChristophWurst** [comment]
Hi,

please see https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html.

For general help with using occ see https://help.nextcloud.com/.

Thanks.
