### ISSUE TITLE
How long is a sent access token valid?

### ISSUE THREAD

**Issue by palto42** [nextcloud/twofactor_gateway#134]
I tried to find out how long an access token sent via the twofactor_gateway (e.g. via Signal) is valid, but it seems it doesn't automatically expire (waited >20 minutes).
Is there an expiry of the sent access tokens and if not, isn't this a security concern?

**Comment by ChristophWurst** [comment]
The code is currently stored in the server session: https://github.com/nextcloud/twofactor_gateway/blob/f9e55f2bd10dc96294e4ea679fdcb08a85eda6d3/lib/Provider/AProvider.php#L92, hence it's TTL depends on the server configuration.

It should be easy to store a generation timestamp together with the code and check expiry on code usage. Would you be interested in adding that?

**Comment by palto42** [comment]
Thanks for your quick response. 
In my view an expiry would be nice to have, but I have nearly no experience with PHP. If I find some time I will give it a try anyway.

**Comment by ChristophWurst** [comment]
Closing as question was ansered
