### ISSUE TITLE
[Mandatory 2FA] Prevent users from disabling 2FA

### ISSUE THREAD

**Issue by kimsyversen** [nextcloud/twofactor_gateway#143]
Hi!

I'm currently testing twofactor_gateway and see users have the possibility remove/change 2FA method in their profiles. I'm adding users via a bash script and I want to force users using 2FA via SMS when I add them. 

How can the possibility to disable 2FA be removed?

**Comment by putt1ck** [comment]
I think mandatory 2FA is now part of NC, but I think it's possible for the user with this app to then not configure any option, which locks them out from next login.
