### ISSUE TITLE
php 7.3...

### ISSUE THREAD

**Issue by luntik2012** [nextcloud/twofactor_gateway#170]
"This app cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 7.2 is required."

**Comment by ChristophWurst** [comment]
Would you be interested in contributing to Nextcloud? This would be a nice and easy task :wink:

**Comment by luntik2012** [comment]
sorry, I do not write php

**Comment by Teutone** [comment]
> Would you be interested in contributing to Nextcloud? This would be a nice and easy task 😉

Could you please elaborate what needs to be done here? Thanks for this nice nextcloud app!

**Comment by ChristophWurst** [comment]
> Just saw #148 so next release will work with 7.3

Right :+1:, I'll push a new release this week.
