### ISSUE TITLE
Integrating eCall SMS Provider

### ISSUE THREAD

**Issue by FabianZihlmann** [nextcloud/twofactor_gateway#173]
@all

I would be very happy, someone could integrate a new SMS provider into the code. Was studying myself but did not get all the details that have to added for a new provider.
I'm using eCall Swiss SMS provider with following url:
https://www.ecall.ch/ecallurl/ecallurl.ASP?WCI=Interface&Function=SendPage&Address=+41791112233&Message=Hello%20World&AccountName=xxx&AccountPassword=yyy

there could be added the parameter "CallingNumber" (e.g. &CallingNumber=+41798887766) as sender number.

So you can see it's very straight forward.
I would really appreciate if someone could help. Would like to use 2FA feature in nextcloud with this provider.

Thanks in advance
Fabian

**Comment by ChristophWurst** [comment]
Have a loot at PRs like https://github.com/nextcloud/twofactor_gateway/pull/169. It's pretty easy to implement a custom gateway.

**Comment by FabianZihlmann** [comment]
Take my chance after #169 has meged to master brunch

**Comment by FabianZihlmann** [comment]
Tried my best with #182.
Unfortunately, I'm not really familliar with github, so I provided a patch for master branch.
Works on our productive Nextcloud-Installation.

Would be great if it could be integrated into the master branch.
Thanks so far
Fabian

**Comment by ChristophWurst** [comment]
Thanks! I'll have a look now :)

**Comment by FabianZihlmann** [comment]
solved by #185
