### ISSUE TITLE
The writing of the app name should be aligned with other existing 2FA apps

### ISSUE THREAD

**Issue by j-ed** [nextcloud/twofactor_gateway#200]
Several different 2FA apps already exist for Nextcloud, like **"Two Factor TOTP"**, **"Two Factor U2F"**. 
Therefore the writing of the app name should be aligned accordingly. I would recommend to rename it
to **"Two Factor Gateway"** (without a dash) instead of **"Two-Factor Gateway"**.

**Comment by ChristophWurst** [comment]
Actually, *Two-Factor* is the correct spelling. This should be fixed at https://github.com/nextcloud/twofactor_u2f/blob/09f10b5dfc14d87acbd7b5f2c69ca84fed886da1/appinfo/info.xml#L4 and https://github.com/nextcloud/twofactor_totp/blob/46dc96bbf4589c222f992e74ce153302af357411/appinfo/info.xml#L5. Could you send a pull request? :)

**Comment by j-ed** [comment]
@ChristophWurst [**x**] pull requests created.

**Comment by ChristophWurst** [comment]
Thank you!
