### ISSUE TITLE
2FA breaks CalDav setup on Mac

### ISSUE THREAD

**Issue by pjrobertson** [nextcloud/twofactor_gateway#249]
I was just having trouble setting up CalDav on MacOS 10.14.5, with my Mac constantly giving 'Unable to verify account name or password' messages when trying to set up CalDav. I'm not sure if this is only an issue with `twofactor_gateway` or if all Nextcloud 2FA apps exhibit this issue. I've also only tried with Telegram, but anyway:

Steps to reproduce:

1. Enable Telegram 2FA in security settings
2. Go to MacOS System Preferences > Internet Accounts > Add New CalDav Account
3. Setup your CalDav account using 'manual/advanced' method entering username, password and URL as per the URL in Calendar app on NextCloud.
4. Click 'Login' and note the error 'Unable to verify account name or password'

After disabling Telegram 2FA I can confirm setup works just fine.

**Comment by ChristophWurst** [comment]
Hi,

you have to use app passwords on MacOS: https://docs.nextcloud.com/server/stable/user_manual/user_2fa.html#using-client-applications-with-two-factor-authentication
