### ISSUE TITLE
websms configured ... and now?

### ISSUE THREAD

**Issue by itverwaltung** [nextcloud/twofactor_gateway#283]
Hi,

i finally succeeded in installing and configuring twofactor gateway for the provider websms.

But i don't have any clue how to link sms.
I checked `occ twhofacoraut:state [user's uid]`:
Two-factor authentication is enabled for user 55B69392-F9D0-4B36-BADB-CF18D3108505

Enabled providers:
- totp
- twofactor_nextcloud_notification
Disabled providers:
- backup_codes
- gateway_signal
- gateway_sms
- gateway_telegram

I see, gateway_sms is disabled for the user.

My next step was to `occ twofactorauth:enable [user's id] gateway_sms`:
Result:
The provider does not support this operation.

What must be done to link gateway_sms and a certain user?

Thanks for your advise.

Alex

```

**Comment by ChristophWurst** [comment]
https://nextcloud-twofactor-gateway.readthedocs.io/en/latest/

the user has to go to their security settings and configure it

**Comment by ChristophWurst** [comment]
This is a bug tracker btw. For support see https://help.nextcloud.com/

**Comment by itverwaltung** [comment]
It seems to be a bug ... in Internet Explorer 11 the user can not see the configuration options. There is only the header "Nachrichten-Gateway-Überprüfung".
![grafik](https://user-images.githubusercontent.com/47498433/66392215-79a6fe00-e9cf-11e9-87ef-b9f85d2e4566.png)



In Firefox everything is fine:

![grafik](https://user-images.githubusercontent.com/47498433/66392287-ac50f680-e9cf-11e9-825c-347716d03669.png)

I was struggling with no option shown in the gui. So i guessed to have all configured with occ.

It is a display problem with Internet Explorer... 

Thanls

Alex

**Comment by ChristophWurst** [comment]
Please open a new ticket at https://github.com/nextcloud/twofactor_gateway/issues/new with info like the version of the app, Nextcloud and the browser console error from IE.

My guess is that we need to include https://github.com/ChristophWurst/browserslist-config-nextcloud.
