### ISSUE TITLE
Require 2 factor only once per web-browser

### ISSUE THREAD

**Issue by ivanol** [nextcloud/twofactor_gateway#295]
This works brilliantly with the various sync clients (Linux/Android/Windows...), asking for the 2-factor auth when we generate the app-password on first setup, and never again afterwards, but it's a bit of a pain with web access.

Is it possible to have the option to set a long-lasting cookie in the browser after a successful 2-factor authentication, so that we don't need another SMS on every web login on the same machine?

**Comment by ChristophWurst** [comment]
-> https://github.com/nextcloud/server/issues/2906 :)
