### ISSUE TITLE
Allow to unconfigure gateways

### ISSUE THREAD

**Issue by ThomasCr** [nextcloud/twofactor_gateway#331]
Hi don't want to setup Signal Gateway and only use Telegram.

But it is not possible to remove the Signal gateway (and others).
```
php7.3 occ twofactorauth:gateway:
  Command "twofactorauth:gateway:" is ambiguous.
  Did you mean one of these?
      twofactorauth:gateway:configure
      twofactorauth:gateway:status
      twofactorauth:gateway:test

php7.3 occ twofactorauth:gateway:status
Signal gateway: configured
SMS gateway: not configured
Telegram gateway: configured

```
And gateways which are not configured should not displayed at the users settings, that admins get not annoyed from user questions like, why not use gateway xy or how can I configure that?!

**Comment by ChristophWurst** [comment]
Sure. PRs are welcome.
