### ISSUE TITLE
Unable to install twofactor_sms in production environment

### ISSUE THREAD

**Issue by Dretech** [nextcloud/twofactor_gateway#37]
Hi Christoph,

In my test nextcloud environment towfactor_sms is running fine. I also wanted to use the two factor sms in my production environment. I followed the steps you gave me (for my test environment) and there are no errors. The logfile data/nextcloud.log does not give new entries. But after entering my password I get the screen below:
![afbeelding](https://user-images.githubusercontent.com/10683755/38496586-6fc93d1a-3bfe-11e8-9aa2-54dee0de0541.png)

Translation: Unable to send message. Try again or contact your administrator.

Can you give me some hints how to solve this problem?

Kind regards,

André

**Comment by ChristophWurst** [comment]
Phew, that is hard to tell. Do you have a debugger set up? Then you could set a break point at https://github.com/nextcloud/twofactor_sms/blob/master/lib/Service/SmsProvider/PlaySMS.php#L69, which is where errors should be caught.

**Comment by Dretech** [comment]
Thanks for your reply. I enables debug in the nextcloud config.php. The last line of data/nextcloud.log is:

`{"reqId":"9A63ynYw4WCWZeLG88Vu","level":3,"time":"2018-04-09T10:38:43+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"include_once(): Failed opening '\/usr\/share\/webapps\/nextcloud\/apps\/twofactor_sms\/appinfo\/..\/vendor\/autoload.php' for inclusion (include_path='\/usr\/share\/webapps\/nextcloud\/3rdparty\/pear\/console_getopt:\/usr\/share\/webapps\/nextcloud\/3rdparty\/pear\/pear_exception:\/usr\/share\/webapps\/nextcloud\/3rdparty\/pear\/pear-core-minimal\/src:\/usr\/share\/webapps\/nextcloud\/3rdparty\/pear\/archive_tar:\/usr\/share\/webapps\/nextcloud\/apps') at \/usr\/share\/webapps\/nextcloud\/apps\/twofactor_sms\/appinfo\/app.php#21","userAgent":"--","version":"13.0.1.1"}

Does that logline give a meaningful explonation why the 2fa is not running?

**Comment by ChristophWurst** [comment]
> include_once(): Failed opening '/usr/share/webapps/nextcloud/apps/twofactor_sms/appinfo/../vendor/autoload.php

Sounds like you did not run `composer install` in the app's directory and thus the `vendor` directory is missing.

**Comment by ChristophWurst** [comment]
Assuming this is resolved -> closing
