### ISSUE TITLE
New release to include clicksend?

### ISSUE THREAD

**Issue by henry-nicolas** [nextcloud/twofactor_gateway#370]
Hello Christoph,

First of all, thanks for this app.
Not sure how feasible it is, but it would be great if you could release an update for this app so that the support for clicksend is shipped to the users.

I noticed it is on the master branch while the last release dates from before the merge request that added this functionnality :-)

Regards,

**Comment by ChristophWurst** [comment]
sure. I'm preparing one today

**Comment by ChristophWurst** [comment]
done https://github.com/nextcloud/twofactor_gateway/releases/tag/v0.17.0
