### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by Tamsy** [nextcloud/twofactor_gateway#375]
Ubuntu 18.04.5 LTS
Apache 2.4.46
PHP 7.4.9
Nextcloud 19.0.1
twofactor_gateway v0.16.0 & v0.17.0

Whenever running ’occ twofactorauth:gateway:configure sms’ I am only getting the following error about a call to a undefined method. 

Has anybody encountered similar or knows what is going wrong here?

 **sudo -u www-data php occ twofactorauth:gateway:configure sms**

Please choose a SMS provider (websms, playsms, clockworksms, puzzelsms, ecallsms, voipms, huawei_e3531, spryng, sms77io, ovh, clickatellcentral, clicksend): An unhandled exception has been thrown:
Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback() in /var/www/cloud/3rdparty/symfony/console/Helper/QuestionHelper.php:119

**Stack trace:**
#0 /var/www/cloud/3rdparty/symfony/console/Helper/QuestionHelper.php(81): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#1 /var/www/cloud/apps/twofactor_gateway/lib/Command/Configure.php(113): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#2 /var/www/cloud/apps/twofactor_gateway/lib/Command/Configure.php(86): OCA\TwoFactorGateway\Command\Configure->configureSms(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/cloud/3rdparty/symfony/console/Command/Command.php(255): OCA\TwoFactorGateway\Command\Configure->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/cloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/cloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\TwoFactorGateway\Command\Configure), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/cloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/cloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/cloud/console.php(100): OC\Console\Application->run()
#9 /var/www/cloud/occ(11): require_once('/var/www/...')

**Comment by ChristophWurst** [comment]
This shounds like a version conflict with another app. Could you try disable all optional apps. Then try this app's command again and gradually enable the other apps until it breaks?

**Comment by Tamsy** [comment]
Thank you for the information. Will do on coming weekend and let you know how it went.

**Comment by ChristophWurst** [comment]
Sure, though the problem is not solved, so other will run into the exact same issue …
