### ISSUE TITLE
Telegram bot not respond on command Start.

### ISSUE THREAD

**Issue by grig27** [nextcloud/twofactor_gateway#405]
I configured everything according to the instructions, the bot does not respond to the start command. The user's phone number is registered, the bot is registered, the key is configured.
How to diagnose a problem?

**Comment by ChristophWurst** [comment]
check the previous tickets. this sounds like a problem someone else asked about recently

**Comment by grig27** [comment]
https://github.com/nextcloud/twofactor_gateway/issues/398
