### ISSUE TITLE
Add Telegram as a 2FA option at first user login

### ISSUE THREAD

**Issue by jofrep** [nextcloud/twofactor_gateway#434]
When 2FA is enforced there is no option for the user to activate the Telegram 2FA at first login.
Other 2FA options like HOTP or Yubikey can be setup by the user during the first login.
Would be good to allow users to add their Telegram User ID

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/twofactor_gateway/issues/239

please always search existing tickets before creating new feature requests

**Comment by jofrep** [comment]
Apologies but although #239 is Open, the functionality is already implemented today but not for Telegram. Shall I open a bug rather than a request for enhancement? Or this is about Telegram although I could find a reference tp it? I don't want to waste your time but to ensure this is properly reported. Thanks

**Comment by ChristophWurst** [comment]
comment it here. I think all the providers lack this support

**Comment by jofrep** [comment]
No, users can autoprovision TOTP at first login (Two-Factor TOTP Provider 5.0.0.) with 20.0.8. I'm confident Yubikey too but would need to test is again once I upgrade PHP

**Comment by ChristophWurst** [comment]
I see. #239 is what you are looking for.

you can trust me, I wrote most of these apps the logic behind them :)

**Comment by jofrep** [comment]
I don't doubt it but I'm sure that yesterday I tested how a user could configure the 2FA for TOTP at first login in an instance where 2FA is mandatory. Yubikey was also offered and I did half of the enrolment too (I did not fully test this case). The only 2FA provider that was not offered at first login was the Telegram. SMS/Signal are not configured, only TOTP, Yubikeys and Telegram.
