### ISSUE TITLE
Please provide compatability for version 21 of NC before giving up/finding replacement

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/twofactor_gateway#455]
Would it at all be possibly to update the app enough so that users relying on it can update to version 21 of nextcloud please?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_gateway/releases/tag/v0.19.0 you're welcome

**Comment by ChristophWurst** [comment]
Forgot to put in on the app store.

**Comment by ChristophWurst** [comment]
Would you like to help maintain the app in the future?

**Comment by 31337-4554551n** [comment]
Thank you!
And I would if I could, really. Sadly, I lack the skillset
