### ISSUE TITLE
Support for NC24 and PHP8.1

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_gateway#492]
On my NC24b3 instance running on Arch linux with PHP 8.1, upon `occ app:enable twofactor_gateway` and despite of adding `twofactor_gateway` to the `app_install_overwrite` array in `config/config.php` I cannot enable the app since this requirement cannot(?) be overruled:
```
cannot be installed because the following dependencies are not fulfilled:
PHP with a version lower than 8.0 is required.
```
While [appinfo/info.xml](https://github.com/nextcloud/twofactor_gateway/blob/master/appinfo/info.xml) reads
```
<nextcloud min-version="21" max-version="24"/>
```
the file packaged in [0.19.0](https://github.com/nextcloud/twofactor_gateway/releases/download/v0.19.0/twofactor_gateway.tar.gz) is different. It reads
```
<php min-version="7.2" max-version="8.0"/> 
<nextcloud min-version="20" max-version="23"/>
```
In the [App Store](https://apps.nextcloud.com/apps/twofactor_gateway), the app is not shown for NC24 nor is it installable using `occ`.

Please change [appinfo/info.xml](https://github.com/nextcloud/twofactor_gateway/blob/master/appinfo/info.xml) to
```
<php min-version="7.3" max-version="8.1"/>
<nextcloud min-version="21" max-version="24"/>
```
according to the most recent [app upgrade guide](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_24.html) and all other files that put restrictions on the app and the visibility in the App Store. I'm not doing a PR since I'm quite unsure what must/should be changed apart from [appinfo/info.xml](https://github.com/nextcloud/twofactor_gateway/blob/master/appinfo/info.xml) – probably [composer.json](https://github.com/nextcloud/twofactor_gateway/blob/master/composer.json)?

Anyway: Manually downloading [0.19.0](https://github.com/nextcloud/twofactor_gateway/releases/download/v0.19.0/twofactor_gateway.tar.gz) and changing [appinfo/info.xml](https://github.com/nextcloud/twofactor_gateway/blob/master/appinfo/info.xml) after extracting it to apps allowed me to enable the app. After doing so, it works perfectly fine for me with NC24 and PHP8.1 for the SMS gateway (using [sms77.io](https://www.sms77.io/)).

**Comment by vitormattos** [comment]
Hi @nursoda send the PR and let's go to see the unit tests working with your changes.
Maybe, you can run locally to look if all will work fine.

**Comment by nursoda** [comment]
https://github.com/nextcloud/twofactor_gateway/pull/493
However, unit tests seem not to be configured properly.

**Comment by vitormattos** [comment]
Will be good migrate the tests on CI to GitHub Actions.
