### ISSUE TITLE
NC24 compatility

### ISSUE THREAD

**Issue by Showfom** [nextcloud/twofactor_gateway#502]
Hello,

Please add compatibility for NC24

**Comment by vitormattos** [comment]
Already solved here: https://github.com/nextcloud/twofactor_gateway/commit/bfabb3b3785b78dc382e49689cfb4c881605b1b5

Will come in the next version

**Comment by Showfom** [comment]
Great, thanks.

**Comment by killerbees19** [comment]
\*push\* 🙂

I think many users would appreciate a new release in the app store. Do you need help with some specific tasks?

@vitormattos @ChristophWurst

**Comment by vitormattos** [comment]
Hi @killerbees19. I think all is done to launch a new release of this app and as a soon we will have a new release. Only is necessary to fix the GitHub Action to deploy the release to Nextcloud appstore, I'm working on this.
