### ISSUE TITLE
NC 24 support?

### ISSUE THREAD

**Issue by hevisko** [nextcloud/twofactor_gateway#514]
Hi there,

 Anybody know if there is anything that will not work with NC 24 ?

**Comment by vitormattos** [comment]
@FelixBuehler you don't need change this. You only need enable untested app.

![image](https://user-images.githubusercontent.com/1079143/176225274-f90d2310-8abb-434e-9ac7-2da7fd8ffbb7.png)

@hevisko we need only fix the GitHub Action to push the new release of this app to Nextcloud appstore, this is a task that I'm is working on.

**Comment by vitormattos** [comment]
Published
