### ISSUE TITLE
No PHP version check on last version (0.20.0)

### ISSUE THREAD

**Issue by hmag** [nextcloud/twofactor_gateway#522]
Having a NextCloud 20.0.6 running on a Debian 10 (PHP version 7.3.31-1~deb10u1), I had installed twofactor_gateway version 0.19.0.
I was proposed by NextCloud to update it to the latest version, which I did.
Then I was stuck with the message "Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.31-1~deb10u1." : not possible to login, my sync applications failed, etc...

After checking, I performed a "occ app:disable twofactor_gateway" to disable the application and now everything is fine... except I don't have anymore the gateway.
So it seems like PHP 7.4 is min is required but this is not checked before installing the app.

Best regards,
Hervé

**Comment by vitormattos** [comment]
Hi @hmag, Nextcloud 20 isn't more supported by this app:
https://github.com/nextcloud/twofactor_gateway/blob/master/appinfo/info.xml#L22
