### ISSUE TITLE
two-factor auth provider 'gateway_telegram' failed to load

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/twofactor_gateway#609]
Hi,

I know there is no more support for this app. I used to use it, but deleted it a long time back.

however my nextcloud.log is still flooding with

two-factor auth provider 'gateway_telegram' failed to load

Could someone please help me delete the remnants of this app?

**Comment by joshtrichards** [comment]
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/two_factor-auth.html#provider-removal

If still stuck, follow-up on the help forum with a few more details - https://help.nextcloud.com
